const OPEN_ADD_WIDGET = 'app/feed/OPEN_ADD_WIDGET';
const CLOSE_ADD_WIDGET = 'app/feed/CLOSE_ADD_WIDGET';
const OPEN_EDIT_WIDGET = 'app/feed/OPEN_EDIT_WIDGET';
const CLOSE_EDIT_WIDGET = 'app/feed/CLOSE_EDIT_WIDGET';
const OPEN_TRUNCATE_WIDGET = 'app/feed/OPEN_TRUNCATE_WIDGET';
const CLOSE_TRUNCATE_WIDGET = 'app/feed/CLOSE_TRUNCATE_WIDGET';

export {
  OPEN_ADD_WIDGET,
  CLOSE_ADD_WIDGET,
  OPEN_EDIT_WIDGET,
  CLOSE_EDIT_WIDGET,
  OPEN_TRUNCATE_WIDGET,
  CLOSE_TRUNCATE_WIDGET,
};
