const GET_POKEMONS = 'app/feed/GET_POKEMONS';
const GET_POKEMONS_SAGA = 'app/feed/GET_POKEMONS_SAGA';
const SET_POKEMONS = 'app/feed/SET_POKEMONS';

export {
  GET_POKEMONS,
  GET_POKEMONS_SAGA,
  SET_POKEMONS,
};
