const GET_POKEMONS = 'app/feed/GET_POKEMONS';
const GET_POKEMONS_SAGA = 'app/feed/GET_POKEMONS_SAGA';
const SET_POKEMONS = 'app/feed/SET_POKEMONS';
const OPEN_ADD_WIDGET = 'app/feed/OPEN_ADD_WIDGET';
const CLOSE_ADD_WIDGET = 'app/feed/CLOSE_ADD_WIDGET';
const ADD_POKEMON_SAGA = 'app/feed/ADD_POKEMON_SAGA';
const ADD_POKEMON = 'app/feed/ADD_POKEMON';
const OPEN_EDIT_WIDGET = 'app/feed/OPEN_EDIT_WIDGET';
const CLOSE_EDIT_WIDGET = 'app/feed/CLOSE_EDIT_WIDGET';
const EDIT_POKEMON_SAGA = 'app/feed/EDIT_POKEMON_SAGA';
const EDIT_POKEMON = 'app/feed/EDIT_POKEMON';
const OPEN_TRUNCATE_WIDGET = 'app/feed/OPEN_TRUNCATE_WIDGET';
const CLOSE_TRUNCATE_WIDGET = 'app/feed/CLOSE_TRUNCATE_WIDGET';
const TRUNCATE_POKEMONS = 'app/feed/TRUNCATE_POKEMONS';

export {
  GET_POKEMONS,
  GET_POKEMONS_SAGA,
  SET_POKEMONS,
  OPEN_ADD_WIDGET,
  CLOSE_ADD_WIDGET,
  ADD_POKEMON,
  ADD_POKEMON_SAGA,
  OPEN_EDIT_WIDGET,
  CLOSE_EDIT_WIDGET,
  EDIT_POKEMON_SAGA,
  EDIT_POKEMON,
  OPEN_TRUNCATE_WIDGET,
  CLOSE_TRUNCATE_WIDGET,
  TRUNCATE_POKEMONS,
};
