const GET_POKEMONS = 'app/feed/GET_POKEMONS';
const GET_POKEMONS_SAGA = 'app/feed/GET_POKEMONS_SAGA';
const SET_POKEMONS = 'app/feed/SET_POKEMONS';
const ADD_POKEMON_SAGA = 'app/feed/ADD_POKEMON_SAGA';
const ADD_POKEMON = 'app/feed/ADD_POKEMON';
const EDIT_POKEMON_SAGA = 'app/feed/EDIT_POKEMON_SAGA';
const EDIT_POKEMON = 'app/feed/EDIT_POKEMON';
const TRUNCATE_POKEMONS = 'app/feed/TRUNCATE_POKEMONS';

export {
  GET_POKEMONS,
  GET_POKEMONS_SAGA,
  SET_POKEMONS,
  ADD_POKEMON,
  ADD_POKEMON_SAGA,
  EDIT_POKEMON_SAGA,
  EDIT_POKEMON,
  TRUNCATE_POKEMONS,
};
